
from django.urls import path
from .views import *

app_name = 'jp1'
urlpatterns = [
    path("index-2/", index_view_2),
    path("index2/", index_2_view),
    path("index3/", index_3_view),
    path("index4/", index_4_view),
    path("404/", html404),
    path("about-us/", about_us),
    path("add-resume/", add_resume),
    path("blog-grid-sidebar/", blog_grid_sidebar),
    path("blog-single-sidebar/", blog_single_sidebar),
    path("blog-single/", blog_single),
    path("bookmarked/", bookmarked),
    path("browse-categories/", browse_categories),
    path("browse-jobs/", browse_jobs),
    path("browse-resumes/", browse_resumes),
    path("change-password/", change_password),
    path("contact/", contact),
    path("faq/", faq),
    path("job-alerts/", job_alerts),
    path("job-details/", job_details),
    path("job-list/", job_list),
    path("mail-success/", mail_success),
    path("manage-applications/", manage_applications),
    path("manage-jobs/", manage_jobs),
    path("manage-resumes/", manage_resumes),
    path("news-standard/", news_standard),
    path("notifications/", notifications),
    path("popper/", popper),
    path("post-job/", post_job),
    path("pricing/", pricing),
    path("privacy-policy/", privacy_policy),
    path("resume/", resume),
    path("terms-conditions/", terms_conditions),
    path("", index_view),
]
